### ISSUE TITLE
Golden lasso / cursed lasso

### ISSUE THREAD

**Issue by zavvias** [b0bst3r/Superstitions#11] opened 2016-11-27 21:26 UTC
Hi,
It seems that there is no golden lasso recipe. Even when i gave myself it and crafted it into cursed lasso i could not catch ghast with 1 health. Is it intended? I couldnt find anything in scripts that would disable it. In eu2 config lassos are enabled.
EDIT - Golden lasso can be crafted despite recipe being not shown. But still seems i cant catch ghast - tested in creative: punched ghast till 1 hearth, cought it , left creative released it and could not catch it with 1 health.

**Comment by b0bst3r** [comment] 2016-11-27 21:47
You catch mobs in the cursed lasso, the golden is for passive animals only, the recipes may be fixed inthe next update as Ex Utils is updated.

**Comment by zavvias** [comment] 2016-11-28 10:07
I know golden is for passives but for me cursed dont work on 1 hearth ghast.

**Comment by b0bst3r** [comment] 2016-11-28 13:23
I reported the recipes but I can't reproduce this with the updated Extra utils, so try it after the update and see if it works for you.

https://github.com/rwtema/extrautilities/issues/1124

**Comment by SyntheticSponge** [comment] 2016-12-08 22:47
The problem with being able to craft it is when you try to craft it in anything but a regular crafting table (i.e refined storage crafting grid). 

If you need the recipe for now, its golden nuggets in the corners and string between the nuggets.

**Comment by b0bst3r** [comment] 2016-12-08 22:53
Yeah that's because it uses your exp to craft it and refined storage and most other crafters wont allow that.

**Closed as completed** 2017-05-29 02:34 UTC
Labels: Cross Mod Bug
